In [12]:
import torch

x = torch.rand(5, 4)
print(x)
print(x[:,2])

x = x.reshape(2,10)
print(x)

tensor([[0.1448, 0.2623, 0.5980, 0.7997],
        [0.5566, 0.7764, 0.2383, 0.0643],
        [0.9416, 0.1858, 0.0895, 0.9805],
        [0.4749, 0.9760, 0.3912, 0.0772],
        [0.1846, 0.8985, 0.1900, 0.5234]])
tensor([0.5980, 0.2383, 0.0895, 0.3912, 0.1900])
tensor([[0.1448, 0.2623, 0.5980, 0.7997, 0.5566, 0.7764, 0.2383, 0.0643, 0.9416,
         0.1858],
        [0.0895, 0.9805, 0.4749, 0.9760, 0.3912, 0.0772, 0.1846, 0.8985, 0.1900,
         0.5234]])
