In [1]:
import torch
import torch.nn.functional as F
import torch.nn as nn

x_train = torch.FloatTensor([ [1,2,1,1], [2,1,3,2], [3,1,3,4], [4,1,5,5], [1,7,5,5], [1,2,5,6], [1,6,6,6], [1,7,7,7] ])
y_train = torch.LongTensor([2,2,2,1,1,1,0,0])
# y_train = torch.FloatTensor([ [0,0,1], [0,0,1], [0,0,1], [0,1,0], [0,1,0], [0,1,0], [1,0,0], [1,0,0] ])

 
W = torch.zeros(4, 3, requires_grad=True)
b = torch.zeros(1, 3, requires_grad=True)
optimizer = torch.optim.Adam([W,b], lr=0.1)

for epoch in range(3001):
  # hypothesis = torch.softmax(torch.mm(x_train, W)+b, dim=1)
  # cost = -torch.mean(torch.sum(y_train * torch.log(hypothesis), dim=1))
  # z = torch.mm(x_train, W)+b
  model = nn.Linear(4,3)  ## 간편하게 선형회귀 표현
  optimizer = torch.optim.Adam(model.parameters(),lr=1)
  z = model(x_train)
  cost = F.cross_entropy(z, y_train)
  hypothesis = (torch.mm(x_train, W)+b).softmax(dim=1)
  # cost = -(y_train * torch.log(hypothesis)).sum(dim=1).mean()

 
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

 
  if epoch % 300 == 0:
    print("epoch: {}, cost: {:.6f}".format(epoch, cost.item()))


## x 가 [1,11,10,9], [1,3,4,3], [1,1,0,1] 일 때, y값은? ##
W.requires_grad_(False)
b.requires_grad_(False)
x_test = torch.FloatTensor([[1,11,10,9], [1,3,4,3], [1,1,0,1]])
test_all = torch.softmax(torch.mm(x_test, W)+b, dim=1)
print(test_all)
print(torch.argmax(test_all, dim=1))




### Softmax Regression in Sklearn ###
## logistic regression, softmax regression are implemented 
## if y_train has more than one kind of value, then softmax regression is executed.

 
import numpy as np
from sklearn.linear_model import LogisticRegression
x_train = np.array([ [1,2,1,1], [2,1,3,2], [3,1,3,4], [4,1,5,5], [1,7,5,5],
                     [1,2,5,6], [1,6,6,6], [1,7,7,7] ])
# y에 0, 1, 2 등 둘 이상의 class가 존재 => softmax regression 
y_train = np.array([ 2, 2, 2, 1, 1, 1, 0, 0 ])
logistic = LogisticRegression() # 모델 생성 
logistic.fit(x_train, y_train) # 학습
pred = logistic.predict([[1,11,10,9], [1,3,4,3], [1,1,0,1]]) # test case (값 예측) 
print(pred) # 출력

epoch: 0, cost: 1.472518
epoch: 300, cost: 1.817991
epoch: 600, cost: 2.386678
epoch: 900, cost: 1.128857
epoch: 1200, cost: 1.713600
epoch: 1500, cost: 1.666236
epoch: 1800, cost: 1.961866
epoch: 2100, cost: 0.998841
epoch: 2400, cost: 1.700381
epoch: 2700, cost: 1.611539
epoch: 3000, cost: 1.590193
tensor([[0.3333, 0.3333, 0.3333],
        [0.3333, 0.3333, 0.3333],
        [0.3333, 0.3333, 0.3333]])
tensor([0, 0, 0])
[0 2 2]
